import requests

data_frame = [
"Tu Hi Meri Shab Hai (Gangster) - K.K - 320Kbps.mp3",
"Tujhe Sochta Hoon (Jannat ) - K.K - 320Kbps.mp3",
"Jannatein Kahan (Jannat ) - K.K - 320Kbps.mp3",
"Kya Mujhe Pyar Hai (Woh Lamhe) - K.K - 320Kbps.mp3",
"Zara Se (Jannat) - K.K - 320Kbps.mp3",
"Door Se Paas (Musafir) - K.K - 320Kbps.mp3",
"Teri Yaadon Mein (The Killer) - K.K - 320Kbps.mp3",
"O Sanam (The Killer) - K.K - 320Kbps.mp3",
"Beetein Lamhein (Live-The Train) - K.K - 320Kbps.mp3",
"Zindagi Do Pal Ki (Kites) - K.K - 320Kbps.mp3",
"Tu Jo Mila (Bajrangi Bhaijaan) - K.K - 320Kbps.mp3",
"Laapata (Ek Tha Tiger) - K.K - 320Kbps.mp3",
"O Humdum Suniyo Re (Saathiya) - K.K - 320Kbps.mp3",
"Dil Kyun Yeh Mera (Kites) - K.K - 320Kbps.mp3",
"Bezubaan - Laali Ki Shaadi (K.K) 320Kbps.mp3",
"Saanson Ke (Raees) - K.K - 320Kbps.mp3",
"O Meri Jaan (Raaz Reboot) - K.K - 320Kbps.mp3",
"Dil Samandar (Garam Masala) - K.K - 320Kbps.mp3",
"Zahreeli Raatein (Chocalate) - K.K - 320Kbps.mp3",
"Khuda Jaane (Bachna Ae Haseeno) - K.K - 320Kbps.mp3",
"Party On My Mind (Race ) - K.K - 320Kbps.mp3",
"Abhi Abhi (Jism ) - K.K - 320Kbps.mp3",
"Dil Nashin Dil Nashin (Aashiq Banaya Aapne) - K.K - 320Kbps.mp3",
"O Jaana (Raaz-TMC) - K.K - 320Kbps.mp3",
"Aye Bekhabar (Zeher) - K.K - 320Kbps.mp3",
"Ajab Si (Om Shanti Om) - K.K - 320Kbps.mp3",
"Dus Bahane (Dus) - K.K - 320Kbps.mp3",
"Beete Lamhein (The Train) - K.K - 320Kbps.mp3",
"Piya Aaye Na (Aashiqui ) - K.K - 320Kbps.mp3",
"Jaavedaan Hai ( - Evil Returns) - K.K - 320Kbps.mp3",
"Sunn Zara - K.K - 320Kbps.mp3",
"Labon Ko (Bhool Bhulaiyaa) - K.K - 320Kbps.mp3",
"Soniye (Aksar) - K.K. - K.K - 320Kbps.mp3",
"Mat Aazma Re (Murder ) - K.K - 320Kbps.mp3",
"Mere Naal (Do Knot Disturb) - K.K - 320Kbps.mp3",
"Bas Ek Pal (Bas Ek Pal) - K.K - 320Kbps.mp3",
"Guzaarish (Guzaarish) - K.K - 320Kbps.mp3",
"Teri Tamanna (The Train) - K.K - 320Kbps.mp3",
"Jhoom Barabar Jhoom (JBJ) - K.K - 320Kbps.mp3",
"Tadap Tadap (Hum Dil De Chuke Sanam) - K.K - 320Kbps.mp3",
"Mere Palak Ka Tu Hi Sitara (Showbiz) - K.K - 320Kbps.mp3",
"Kabhi Aayine Pe (Hate Story ) - K.K - 320Kbps.mp3",
"Hai Junoon (New York) - K.K - 320Kbps.mp3",
"I Am In Love (OUATIM) - K.K - 320Kbps.mp3",
"Tum Ho Mera Pyar (Haunted) - K.K - 320Kbps.mp3",
"Jeena Isi Ka Naam Hai - K.K - 320Kbps.mp3",
"Tuhi Mere Hum Navaa (Knock Out) - K.K - 320Kbps.mp3",
"Aaya Re (Jashnn) - K.K - 320Kbps.mp3",
"Make Some Noise (Desi Boyz) - K.K - 320Kbps.mp3",
"Dillagi Mein Jo Beet Jaaye (ABA) - K.K - 320Kbps.mp3",
"Soniye (Heartless) - K.K - 320Kbps.mp3",
"Mere Khuda (Sorry Bhai) - K.K - 320Kbps.mp3",
"Aksar (Hijack) - K.K - 320Kbps.mp3",
"Ae Aa O (Billu) - K.K - 320Kbps.mp3",
"Ab To Forever (Tara Rum Pum) - K.K - 320Kbps.mp3",
"Meri Maa (Yaariyan) - K.K - 320Kbps.mp3",
"Luk Chup Jaana (Action Replay) - K.K - 320Kbps.mp3",
"Duniya Ne Dil (Showbiz) - K.K - 320Kbps.mp3",
"Yaara Re (Roy) - K.K - 320Kbps.mp3",
"Aasman Ke (Humsafar) - K.K - 320Kbps.mp3",
"Pakeeza (Ek Tera Saath) - K.K - 320Kbps.mp3",
"Jeetne Ke Liye (Azhar) - K.K - 320Kbps.mp3",
"Mera Pehla Pehla Pyaar (MP) - K.K - 320Kbps.mp3",
"Afreen (Bhagam Bhaag) - K.K - 320Kbps.mp3",
"Pal (Live) - K.K - 320Kbps.mp3",
"Ayaashi (Badmaash Company) - K.K - 320Kbps.mp3",
"Bin Tum (Dus Kahaniyaan) - K.K - 320Kbps.mp3",
"Fanah (Humko Deewana Kar Gaye) - K.K - 320Kbps.mp3",
"Allah Hafiz (Bhool Bholiyaan) - K.K - 320Kbps.mp3",
"Tadap Tadap (Live) - K.K - 320Kbps.mp3",
"Tujh Sang Lagee (Special ) - K.K - 320Kbps.mp3",
"Tujhi Mein (Crook) - K.K - 320Kbps.mp3",
"O Meri Jaan (Life in a Metro) - K.K - 320Kbps.mp3",
"Main Kya Hoon (Love Aaj Kal) - K.K - 320Kbps.mp3",
"Nazrein Karam (Jashnn) - K.K - 320Kbps.mp3",
"Ek Pal Mein (Hattrick) - K.K - 320Kbps.mp3",
"Khuda Mere Khuda (Krantiveer) - K.K - 320Kbps.mp3",
"Tere Bin Ho Na Sakega Gujara - K.K - 320Kbps.mp3",
"Lagdaa Naa Lagdaa (Bhram) - K.K - 320Kbps.mp3",
"O Meri Jaan (Tum Mile) - K.K - 320Kbps.mp3",
"Allah Beli (My Name Is Anthony Gonsalves) - K.K - 320Kbps.mp3",
"Main Tera Dhadkan Teri (Ajab Prem...Kahani) - K.K - 320Kbps.mp3",
"Jaane Kiske Khwaab (Guzaarish) - K.K - 320Kbps.mp3",
"Touch Me (Dhoom ) - K.K - 320Kbps.mp3",
"Mere Brother Ki Dulhan (MBKD) - K.K - 320Kbps.mp3",
"Yaaron - (Live) - K.K - 320Kbps.mp3",
"Alvida (Life...Metro) - K.K - 320Kbps.mp3",
"Dil Aaj Kal (Purani Jeans) - K.K - 320Kbps.mp3",
"Humko Pyaar Hua (Ready) - K.K - 320Kbps.mp3",
"Aafreen ( - London) - K.K - 320Kbps.mp3",
"Mujhko Pehchaanlo (Don ) - K.K - 320Kbps.mp3",
"Neal n Nikki (Neal n Nikki) - K.K - 320Kbps.mp3",
"Tere Bin (Bandish) - K.K - 320Kbps.mp3",
"O Mama ( Khoon Maaf) - K.K - 320Kbps.mp3",
"Pad Gaye Ji (Akaash Vani) - K.K - 320Kbps.mp3",
"Koi Kahe Kehta Rahe (Dil Chahta Hai) - K.K - 320Kbps.mp3",
"Chahoon Tujhe - K.K - 320Kbps.mp3",
"Ek Pal Ke Liye (Ankahee) - K.K - 320Kbps.mp3",
"Sajde (Khatta Meetha) - K.K - 320Kbps.mp3",
"Kaise Bataaoon (G) - K.K - 320Kbps.mp3",
"Golmaal (Golmaal Returns) - K.K - 320Kbps.mp3",
"O Maahiya (Dus Kahaniyaan) - K.K - 320Kbps.mp3",
"Jaane Kaise (Raqeeb) - K.K - 320Kbps.mp3",
"Haan Main Jitni Martaba (All The Best) - K.K - 320Kbps.mp3",
"Mere Bina (Crook) - K.K - 320Kbps.mp3",
"Kaise Ye Raaz Hai (Raaz - TMC) - K.K - 320Kbps.mp3",
"Rafta Rafta (Raaz ) - K.K - 320Kbps.mp3",
"Khwabon Khwabon (Force) - K.K - 320Kbps.mp3",
"Haan Tu Hain (Jannat) - K.K - 320Kbps.mp3"
]

base_url = "https://pwdown.com/11981/"

for song in data_frame:
  song_url = base_url + song
  print(song_url)

  r = requests.get(song_url, allow_redirects=True)
  open(song, 'wb').write(r.content)
